-- SELECT 
-- 3월에 태어난 여성 회원 목록 출력하기
-- Level 2 17,480명 완료
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TO_CHAR(DATE_OF_BIRTH, 'MM')='03' AND GENDER = 'W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC
 
-- 12세 이하인 여자 환자 목록 출력하기
-- Level 1 16,396명 완료
-- NVL(TLNO,'NONE') TNLO가 NULL이면 NONE 출력
SELECT PT_NAME, PT_NO, GEND_CD, AGE, NVL(TLNO,'NONE') AS TLNO
FROM PATIENT
WHERE AGE <=12 AND GEND_CD ='W'
ORDER BY AGE DESC, PT_NAME ASC
 
-- 평균 일일 대여 요금 구하기
-- Level 1 14,372명 완료
SELECT ROUND(AVG(DAILY_FEE)) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV'

-- 인기있는 아이스크림
-- Level 1 17,235명 완료
SELECT FLAVOR
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC 

-- 조건에 맞는 도서 리스트 출력하기
-- Level 1 14,198명 완료
SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK 
WHERE TO_CHAR(PUBLISHED_DATE, 'YYYY') = '2021' AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC;

-- 조건에 부합하는 중고거래 댓글 조회하기
-- Level 1 12,931명 완료
SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, TO_CHAR(UGR.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD UGB, USED_GOODS_REPLY UGR
WHERE UGB.BOARD_ID = UGR.BOARD_ID AND TO_CHAR(UGB.CREATED_DATE,'YYYY-MM') ='2022-10'
ORDER BY UGR.CREATED_DATE ASC, UGB.TITLE ASC

-- 과일로 만든 아이스크림 고르기
-- Level 1 16,338명 완료
SELECT FH.FLAVOR
FROM FIRST_HALF FH, ICECREAM_INFO II
WHERE FH.FLAVOR = II.FLAVOR AND FH.TOTAL_ORDER > 3000 AND II.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC

-- 서울에 위치한 식당 목록 출력하기
-- Level 4 10,954명 완료
SELECT RI.REST_ID, RI.REST_NAME,RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO RI, REST_REVIEW RR
WHERE RI.REST_ID = RR.REST_ID AND RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID, RI.REST_NAME,RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS
ORDER BY SCORE DESC, RI.FAVORITES DESC
 
-- 흉부외과 또는 일반외과 의사 목록 출력하기
-- Level 1 15,639명 완료
SELECT DR_NAME, DR_ID, MCDP_CD, TO_CHAR(HIRE_YMD,'YYYY-MM-DD') AS HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD IN ('CS', 'GS')
ORDER BY HIRE_YMD DESC, DR_NAME ASC

-- 강원도에 위치한 생산공장 목록 출력하기
-- Level 1 19,172명 완료
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE '%강원도%'
ORDER BY FACTORY_ID ASC
 
-- 재구매가 일어난 상품과 회원 리스트 구하기
-- Level 2 15,135명 완료
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(USER_ID)>=2
ORDER BY USER_ID ASC, PRODUCT_ID DESC
 
-- 모든 레코드 조회하기
-- Level 1 75,588명 완료
SELECT *
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC

-- 오프라인/온라인 판매 데이터 통합하기
-- Level 4 11,457명 완료
SELECT TO_CHAR(A.SALES_DATE,'YYYY-MM-DD') AS SALES_DATE, A.PRODUCT_ID, A.USER_ID, A.SALES_AMOUNT
FROM (SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
     FROM ONLINE_SALE
     WHERE TO_CHAR(SALES_DATE,'YYYY-MM')='2022-03'
     UNION
 SELECT NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
 FROM OFFLINE_SALE
 WHERE TO_CHAR(SALES_DATE,'YYYY-MM')='2022-03'
     ) A
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
 
-- 역순 정렬하기
-- Level 1 69,083명 완료
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC
 
-- 아픈 동물 찾기
-- Level 1 67,961명 완료
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'
ORDER BY ANIMAL_ID
 
-- 어린 동물 찾기
-- Level 1 65,121명 완료
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged'
ORDER BY ANIMAL_ID

-- 동물의 아이디와 이름
-- Level 1 62,272명 완료
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID
 
-- 여러 기준으로 정렬하기
-- Level 1 60,297명 완료
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME ASC, DATETIME DESC

-- 상위 n개 레코드
-- Level 1 59,680명 완료
SELECT NAME
FROM (SELECT * FROM ANIMAL_INS ORDER BY DATETIME ASC)
WHERE ROWNUM = 1
 
-- 조건에 맞는 회원수 구하기
-- Level 1 18,343명 완료
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE TO_CHAR(JOINED,'YYYY') = '2021' AND AGE BETWEEN  20 AND 29
