-- 경기도에 위치한 식품창고 목록 출력하기
-- Level 1 14,574명 완료
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, NVL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID ASC
 
-- 이름이 없는 동물의 아이디
-- Level 1 48,056명 완료
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY ANIMAL_ID ASC
 
-- 이름이 있는 동물의 아이디
-- Level 1 47,429명 완료
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID ASC
 
-- NULL 처리하기
-- Level 2 44,147명 완료
SELECT ANIMAL_TYPE, NVL(NAME,'No name'), SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID	
 
-- 나이 정보가 없는 회원 수 구하기
-- Level 1 14,973명 완료
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE AGE IS NULL