-- 주문량이 많은 아이스크림들 조회하기
-- Level 4 8,742명 완료
 
-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
-- Level 4 4,171명 완료
 
-- 5월 식품들의 총매출 조회하기
-- Level 4 8,633명 완료
 
-- 조건에 맞는 도서와 저자 리스트 출력하기
-- Level 2 13,551명 완료
SELECT B.BOOK_ID, A.AUTHOR_NAME	, TO_CHAR(B.PUBLISHED_DATE,'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK B LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE ASC
 
-- 그룹별 조건에 맞는 식당 목록 출력하기
-- Level 4 8,305명 완료
 
-- 없어진 기록 찾기
-- Level 3 46,239명 완료
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO LEFT JOIN ANIMAL_INS AI ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID, AO.NAME
 
-- 있었는데요 없었습니다
-- Level 3 43,679명 완료
SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AI LEFT OUTER JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME < AI.DATETIME
ORDER BY AI.DATETIME ASC
 
-- 오랜 기간 보호한 동물(1)
-- Level 3 40,054명 완료
SELECT AI.NAME, AI.DATETIME
FROM ANIMAL_INS AI LEFT OUTER JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.ANIMAL_ID IS NULL
ORDER BY DATETIME ASC
 
-- 보호소에서 중성화한 동물
-- Level 4 36,524명 완료
SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI, ANIMAL_OUTS AO
WHERE AI.ANIMAL_ID = AO.ANIMAL_ID AND (AI.SEX_UPON_INTAKE LIKE '%Intact%' AND REGEXP_LIKE(AO.SEX_UPON_OUTCOME,'Spayed|Neutered'))
ORDER BY ANIMAL_ID ASC
 
-- 상품 별 오프라인 매출 구하기
-- Level 2 13,526명 완료
SELECT PRODUCT_CODE, SUM(P.PRICE*OS.SALES_AMOUNT) AS SALES
FROM PRODUCT P LEFT JOIN OFFLINE_SALE OS ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC
 
-- 상품을 구매한 회원 비율 구하기
-- Level 5 5,574명 완료